add exclusion filter
ubports/history-service pull request #25
Opened 2020-07-06 19:18 UTC by lduboeuf

As i don't get crosbuilder working to build locally, i use CI...

2020-07-07 10:48 UTC, lduboeuf commented
humm so it seems the tests are still unstable, as i didn't modify to the DaemonTest, why now it is not ok anymore :-[ ?

2020-07-07 16:25 UTC, mardy requested changes
Can you better explain the first commit? Why are you using `ctest` directly?

2020-07-07 16:25 UTC, mardy commented on tests/plugins/sqlite/SqliteEventViewTest.cpp
> +        for(const auto& event : events)
space after `for`

2020-07-07 16:25 UTC, mardy commented on tests/plugins/sqlite/SqliteEventViewTest.cpp
> +           QVERIFY(event[History::FieldMessageStatus].toString() != History::MessageStatusDraft);
let's use 4 spaces for the indentation

2020-07-07 17:32 UTC, lduboeuf commented
> Can you better explain the first commit? Why are you using `ctest` directly?

because DaemonTest was not working with test :).... I will try again to undo

2020-07-07 17:56 UTC, lduboeuf commented
@mardy as you see, the tests fails when doing with `test` :-/

2020-07-08 17:30 UTC, mardy approved these changes
Thanks, this looks very good! Can I merge it, or are you still working on it?

2020-07-08 20:00 UTC, lduboeuf commented
> Thanks, this looks very good! Can I merge it, or are you still working on it?

no it is fine you can merge it

2020-07-09 05:59 UTC, mardy commented
> no it is fine you can merge it, will you update the changelog ?

No, it's better if you do it, you know better how to describe the changes :-)

2020-07-09 05:59 UTC, merged